Addressing feedback on `RewardsManager.vy`
maddevsio/lido pull request #2
Opened 2021-08-27 12:00 UTC by pavelis

RewardsManager.vy:

* `out_of_funding_date()` renamed to `period_finish()`.
* `GIFT_INDEX`/`gift_index` is now constant, removed extra fixtures and tests.
* Struct instead of tuple in `_period_finish()`
* Added events: `OwnershipTransferred`, `RewardsContractSet`, `ERC20TokenRecovered`
* Added events testing, `recover_erc20()` made staking-rewards-sushi-style.

2021-08-27 12:30 UTC, blitz-1306 approved these changes

2021-08-27 12:30 UTC, blitz-1306 commented on contracts/RewardsManager.vy
>      assert msg.sender == self.owner, "not permitted"
I guess could possibly be cheaper to compare to `old_owner` instead of `self.owner` here.

2021-08-27 12:30 UTC, blitz-1306 commented on contracts/RewardsManager.vy
> +    return self._period_finish(self.rewards_contract)
I'm wondering if we can inline `_period_finish()`'s implementation to the external method only, as we not using it internally anywhere else.

2021-08-27 12:31 UTC, blitz-1306 approved these changes
Good job. Lets ask external reviewers what they think.

2021-08-27 12:34 UTC, blitz-1306 commented
@psirex @bulbozaur please, take a look.

2021-08-27 13:02 UTC, pavelis commented on contracts/RewardsManager.vy
>      assert msg.sender == self.owner, "not permitted"
Cheaper in gas?

2021-08-27 13:06 UTC, bulbozaur commented on contracts/RewardsManager.vy
> +event OwnershipTransferred:
It's better to emit events also in constructor, to have ability to restore full state from events without custom handlers

2021-08-27 14:52 UTC, pavelis commented on contracts/RewardsManager.vy
> +    return self._period_finish(self.rewards_contract)
I thought so, but decided not to delete the internal method because it is used by other methods and you cannot call external method via 'self'.

2021-08-28 06:18 UTC, pavelis commented on contracts/RewardsManager.vy
>      assert msg.sender == self.owner, "not permitted"
OK, confirmed:

`transfer_ownership         -  avg:   22581  avg (confirmed):   22240  low:   14747  high:   29734` (self.owner)

vs

`transfer_ownership         -  avg:   21917  avg (confirmed):   21643  low:   14349  high:   28937` (old_owner)

2021-08-30 03:46 UTC, blitz-1306 requested changes
One other suggestion.

2021-08-30 03:46 UTC, blitz-1306 commented on contracts/RewardsManager.vy
> +    log OwnershipTransferred(ZERO_ADDRESS, msg.sender)
I guess we miss another event here:
```vyper
log RewardsContractSet(_rewards_contract)
```
Otherwise, do we really use this event anywhere?

2021-08-30 10:30 UTC, blitz-1306 approved these changes
Looks good to me

2021-08-30 13:26 UTC, bulbozaur approved these changes

2021-08-30 14:40 UTC, Psirex commented on tests/test_rewards_manager.py
>  def test_owner_recovers_erc20_to_own_address(rewards_manager, ldo_token, ape):
Seems like the implementation for this test case is missing.

2021-08-30 14:40 UTC, Psirex commented on tests/test_rewards_manager.py
> +    assert tx.events[0]['new_owner'] == stranger
It's better to check events by name via `tx.events['OwnershipTransferred']['new_owner']`. Also in this test case check for `previous_owner` is missing.

2021-08-31 09:42 UTC, pavelis commented on tests/test_rewards_manager.py
>  def test_owner_recovers_erc20_to_own_address(rewards_manager, ldo_token, ape):
Sure!

2021-08-31 11:45 UTC, Psirex commented on tests/test_rewards_manager.py
> +    assert tx.events['OwnershipTransferred']['new_owner'] == stranger
Assertion for `previous_owner` in the event still is missing

2021-09-01 09:24 UTC, bulbozaur approved these changes

2021-09-02 04:12 UTC, blitz-1306 approved these changes

2021-09-02 05:51 UTC, merged